version: "3.6"

services:
  # hbase
  pinpoint-hbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PINPOINT_VERSION=${PINPOINT_VERSION}

    container_name: "${PINPOINT_HBASE_NAME}"
    #image: "pinpointdocker/pinpoint-hbase:${PINPOINT_VERSION}"

    volumes:
      - /home/pinpoint/hbase
      - /home/pinpoint/zookeeper
    expose:
      # HBase Master API port
      - "60000"
      # HBase Master Web UI
      - "16010"
      # Regionserver API port
      - "16201"
      # HBase Regionserver web UI
      - "16030"
      # Regionserver web UI port
      - "16301"
    ports:
      - "${EXTERNAL_HBASE_PORT:-2181}:2181"
      - "60001:60000"
      - "26010:16010"
      - "16030:16030"
      - "16301:16301"
      - "16201:16201"
    restart: always
    networks:
      - pinpoint

  # zookeeper            
  pinpoint-zookeeper:
    image: zookeeper:3.4
    expose:
      - "2181"
    ports:
      - "21818:2181"
    restart: always
    networks: 
      - pinpoint

networks:
  pinpoint:       
    driver: bridge

